name: PostDeploy

on: 
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use secret
      env:
        API_KEY: ${{ secrets.API_KEY }}
